dist: trusty
branches:
  only:
    - master
    # tags
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/

language: node_js
node_js:
  - 6
  - 8
  - 10

script:
  - npm run lint
  - npm test
  - npm run test-ts
  - npm run coverage

after_success:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js

deploy:
  provider: npm
  email: ostrovski.alex@gmail.com
  api_key: $NPM_KEY
  on:
    tags: true
